### T1 [1 балл]. Сделайте калькулятор произвольных выражений, операции следующие: +, -, /, ^, *. скобок нет

In [1]:
def calculate(input_str = "0"):  
    # Удаляем пробелы из строки
    nosp=input_str.replace(" ","")
    res = []
    n = 0
    # Формируем список операндов и действий
    for i in range(len(nosp)):
        if nosp[i] in ("+", "-", "*", "/", "^"):
            res.append(int(nosp[n:i]))
            res.append(nosp[i])
            n = i + 1 # позиция очередного числа в строке
    res.append(int(nosp[n:]))
    # Выполняем действия в приоритетном порядке
    # Выполняем возведение в степень справа налево (1 приоритет)
    for i in range(len(res)-1,0,-1):
        if res[i] == "^":
            res[i-1] = res[i-1]**res[i+1]
            # Удаляем из списка 2 элемента: второй аргумент и символ функции (мат.действие)
            res.pop(i+1)
            res.pop(i)
    # Выполняем умножение и деление (2 приоритет)
    for i in range(len(res)):
        while i < len(res) and res[i] in ("*", "/"):
            if res[i] == "*":
                res[i-1] = res[i-1]*res[i+1]
            else:
                res[i-1] = res[i-1]/res[i+1]
            res.pop(i+1)
            res.pop(i)
    # Выполняем сложение и вычитание (3 приоритет)
    for i in range(len(res)):
        while i < len(res) and res[i] in ("+", "-"):
            if res[i] == "+":
                res[i-1] = res[i-1]+res[i+1]
            else:
                res[i-1] = res[i-1]-res[i+1]
            res.pop(i+1)
            res.pop(i)                         
    return res[0]

#### Дополнить еще 2-мя своими тестами

In [2]:
assert calculate("2 + 2 * 2") == 6
assert calculate("345 / 5 * 21") == 1449.
assert calculate("3^3 - 10 + 41 * 3") == 140
assert calculate("42 / 7 * 32") == 192.0
assert calculate("2^3^2") == 512
assert calculate("19 + 98*3 - 4^2 / 8") == 311

### T2 [1 балл]. Создайте функцию, которая размножает букву, после которой встретилось число, на это число.
HE2LO -> HELLO (число означает сколько раз встречается буква)

In [3]:
def transform_string(inp_string):
    # Изначально строчка пустая
    res = ""
    n = 0 # счетчик повторов буквы, изначально пустой
    for i in range(len(inp_string)):
        # Идем по строке и ищем число
        if not inp_string[i].isdigit():
            if n == 0:
                # Если счетчика не было, печатаем букву 1 раз
                n = 1
            # Если счетчик был, печатаем букву n раз
            res = res+inp_string[i]*n
            n = 0
        # Если у счетчика больше 1 разряда
        else:
            n = n*10 + int(inp_string[i])
    return res

#### Дополнить еще 2-мя своими тестами

In [4]:
assert transform_string("HE2LO") == "HELLO"
assert transform_string("HI") == "HI"
assert transform_string("пр12ивет") == "приииииииииииивет"
assert transform_string("2л3у78н65тик") == 'ллуууннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннннтттттттттттттттттттттттттттттттттттттттттттттттттттттттттттттттттик'
assert transform_string("1one2twothr3ef4ourf5ivesi6xse7ven8eightnin9e") == "onettwothreeefoooourfiiiiivesixxxxxxsevvvvvvveneeeeeeeeightnineeeeeeeee"
assert transform_string("Финальный2 тест100.") == 'Финальный  тест....................................................................................................'

### T3 [1 балл]. Создайте функцию, которая выводит статистик по строке: кол-во гласных, согласных, цифр, строчных букв, прописных букв

In [5]:
def string_stat(inp_string):
    # Ъ и Ь не относятся ни к гласным, ни к согласным
    vowels = "aeiouyаеёиоуыэюя"
    consonants ="bcdfghjklmnpqrstvwzxбвгджзйклмнпрстфхцчшщ"
    vc = 0 # счетчик гласных
    cc = 0 # счетчик согласных
    dig = 0 # счетчик цифр
    upc = 0 # счетчик заглавных букв
    lwc = 0 # счетчик строчных букв
    for i in range(len(inp_string)):
        if vowels.find(inp_string[i].lower()) != -1:
            vc += 1
        if consonants.find(inp_string[i].lower()) != -1:
            cc += 1
        if inp_string[i].isdigit():
            dig += 1
        if inp_string[i].islower():
            lwc += 1
        if inp_string[i].isupper():
            upc += 1
        continue
    return (vc, cc, dig, lwc, upc)

#### Дополнить еще 2-мя своими тестами

In [6]:
assert string_stat("Тевирп") == (2, 4, 0, 5, 1)
assert string_stat("КоРоВа4") == (3, 3, 1, 3, 3)
assert string_stat("один1 два2 три3 четыре4 пять5") == (8, 11, 5, 20, 0)
assert string_stat("LetsCheckItOut....") == (5, 9, 0, 10, 4)

### Т4 [1 балл]. Напишите функцию, инвертирующую словарь.
Например, из k - [v_1, v_2] в v_1 - [k_1]

In [7]:
def dict_inverter(input_dict):
    res = dict() # cоздаем пустой словарь
    # Список всех значений
    for aval in input_dict.values():
        # Конкретное значение из общего списка
        for val in aval:
            # Создаем пустой список значений инвертируемого списка
            keys = list()
            # Ищем конкретное значение у всех ключей
            for item in input_dict.items():
                for j in range (len(item[1])):
                    # Заносим ключ в список значений
                    if item[1][j] == val:
                        keys.append(item[0])
            # Если список состоит из 1 элемента, преобразуем его в элемент без списка
            res[val] = keys[0] if len(keys) == 1 else keys
    return res

#### Дополнить еще 1-м своим тестом

In [8]:
assert dict_inverter({"mango" : ["eatable"], "pillow": ["sleepable"]}) == {"eatable": "mango", "sleepable": "pillow"}
assert dict_inverter({"mango" : ["eatable", "readable"]}) == {"readable":"mango", "eatable":"mango"}
assert dict_inverter({"mango" : ["eatable"], "banana": ["eatable"]}) == {"eatable": ["mango", "banana"]}
assert dict_inverter({"mango" : ["eatable", "readable"], "banana": ["eatable", "readable"], "pillow": ["sleepable", "readable"]}) == {'eatable': ['mango', 'banana'], 'readable': ['mango', 'banana', 'pillow'], 'sleepable': 'pillow'}

### T5 [2 балла]. Средствами NumPy реализуйте функцию для применения метода главных компонент (снижение размерности).
На вход подается двумерная матрица (NxM) и число компонент (k), на выходе получите матрицу сниженной размерности (Nxk)
https://medium.com/analytics-vidhya/understanding-principle-component-analysis-pca-step-by-step-e7a4bb4031d9
#### Протестируйте ее на некоторой матрице

In [9]:
import numpy as np

# Задаём массив и переменную k
array = np.array([[5.1,10.2,3.0,48.2,20.6],[4.4,5.5,6.6,7.7,8.8],[19.2,1.0,31.7,8.8,21.2],[5.2,17.9,26.5,45.3,11.1]])
k = 2
print("Первоначальная матрица: \n",array,"\n")

# Пишем функцию стандартизации массива
def standardize_data(array):
    rows, columns = array.shape # кортеж
    standArray = np.zeros(shape=(rows, columns))
    tempArray = np.zeros(rows)
    for column in range(columns):
        mean = np.mean(array[:,column])
        std = np.std(array[:,column])
        tempArray = np.empty(0)
        for element in array[:,column]:
            tempArray = np.append(tempArray, ((element - mean) / std))
        standArray[:,column] = tempArray
    return standArray

# Стандартизируем массив
array = standardize_data(array)

# Вычисляем ковариантную матрицу, транспонируя массив
covariance_matrix = np.cov(array.T)

# Вычисляем собственные значения и собственные векторы ковариатной матрицы
eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

# Вычисляем объясненную дисперсию для каждого компонента
variance_explained = []
for i in eigen_values:
     variance_explained.append((i/sum(eigen_values))*100)
        
# Вычисляем кумулятивную сумму дисперсий
cumulative_variance_explained = np.cumsum(variance_explained)

# Берём первые k компонентов компонента
projection_matrix = (eigen_vectors.T[:][:k]).T

# Получаем матрицу сниженной размерностиы
array_pca = array.dot(projection_matrix)
print("Матрица сниженной размерности: \n",array_pca,"\n")

Первоначальная матрица: 
 [[ 5.1 10.2  3.  48.2 20.6]
 [ 4.4  5.5  6.6  7.7  8.8]
 [19.2  1.  31.7  8.8 21.2]
 [ 5.2 17.9 26.5 45.3 11.1]] 

Матрица сниженной размерности: 
 [[-0.97550149 -0.59900277]
 [-0.33217652  1.93502116]
 [ 2.77860643 -0.44869544]
 [-1.47092842 -0.88732295]] 



### Т6 [4 балла]. Напишите в виде класса NashNumPy свой NumPy, но выполняющий матричные операции только на одномерных и двумерных массивах. Должны быть реализованы следующие операции (в случае, если по правилам линейной алгебры такая операция невозможна, то должна возвращаться соответствующая ошибка):
- создание объекта класса NashNumPy - через список, через заполнение 0, через заполнение 1
- красивое распечатывание объекта класса
- применение некоторой (подаваемой на вход) функции ко всем элементам массива
- размерность объекта класса
- матричное сложение (и разность)
- матричное произведение
- произведение Адамара
- вертикальное соединение
- горизонтальное соединение

#### Напишите собственные проверки работоспособности функции

In [10]:
# Берём стандартные операторы (заданием не запрещено)
from operator import sub, mul

class NashNumPy:
    # Создаем подкласс для выполнения инициализации массива    
    class ndarray:
        def __init__(self):
            self.array = [] # наполнение массива
            self.ndim = 0 # число измерений (список или двумерный массив)
            self.shape = (1,) # размерность массива
        # Метод создания массива, когда на вход передаётся готовый массив    
        def iarray(self,data):
            self.ndim = 2
            # Проверяем, существует ли у массива второе измерение
            try:
                i = len(data[0])
            except TypeError:
                self.ndim = 1
            self.array = data
            if self.ndim == 1:
                self.shape = (len(data),)
            else:
                self.shape = ( len(data), len(data[0]))
        # Метод для заполнения массива нулями    
        def izeros(self,size):
            if isinstance(size, list):
                self.ndim = 2
                self.array = [[0 for j in range(size[1])] for i in range(size[0])]
                self.shape = (size[0],size[1])
            else:
                self.ndim = 1
                self.array = [0] * size
                self.shape = (size,)
        # Метод для заполнения массива единицами        
        def iones(self,size):
            if isinstance(size, list):
                self.ndim = 2
                self.array = [[1 for j in range(size[1])] for i in range(size[0])]
                self.shape = (size[0],size[1])
            else:
                self.ndim = 1
                self.array = [1] * size
                self.shape = (size,)
        # Убираем запятые и выравниванием элементы массива по самому длинному элементу
        def __str__(self):
            s="" # Результирующая строка
            lmax = 0 # Самый длинный элемент массива
            if self.ndim == 2:
                # Ищем масксимум и по строчкам и по столбцам
                for i in range(len(self.array)): 
                    for j in range(len(self.array[0])):
                        if lmax < len(str(self.array[i][j])):
                            lmax = len(str(self.array[i][j]))
                # Формируем строки массива с двумя измерениями
                for i in range(len(self.array)):
                    s = s + "[" # каждая строка начинается с открывающейся квадратной скобки
                    for j in range(len(self.array[0])):
                        s2 = str(self.array[i][j]) # формируем строковое представление элемента массива [i][j]
                        # Дополняем строку пробелами слева до максимального размера
                        s = s + " " * (lmax - len(s2) + 1) + s2
                    s = s + " ]"
                    # Перевод строки в конце каждой строчки кроме последней
                    if i < (len(self.array))-1:
                        s = s + "\n"
            else:
                # Формируем строку (массив с одним измерением)
                for i in range(len(self.array)):
                    if lmax < len(str(self.array[i])):
                        lmax = len(str(self.array[i]))
                s="["
                for i in range(len(self.array)):
                    s2 = str(self.array[i])
                    s = s + " " * (lmax - len(s2) + 1) + s2
                s = s + " ]"
            return s
        # Применение некоторой (подаваемой на вход) функции ко всем элементам массива     
        def vectorize(self, func):
            if self.ndim == 1:
                self.array = list(map(func, self.array))
            else:
                r = []
                for row in self.array:
                    row = list(map(func, row))
                    r.append( row )
                self.array = r
        # Заменяем оператор сложения        
        def __add__(self,new):
            if self.shape != new.shape:
                    return("Размеры массивов не совпадают")
            if self.ndim == 2:
                res = [[self.array[i][j] + new.array[i][j]  for j in range (len(self.array[0]))] for i in range(len(self.array))] 
            else:
                res = [sum(i) for i in zip(self.array,new.array)]
            a = NashNumPy.ndarray()
            a.iarray(res)
            return a
        # Заменяем оператор вычитания
        def __sub__(self,new):
            if self.shape != new.shape:
                    return("Размеры массивов не совпадают")
            if self.ndim == 2:
                res = [[self.array[i][j] - new.array[i][j] for j in range (len(self.array[0]))] for i in range(len(self.array))] 
            else:
                res = list(map(sub,self.array,new.array))
            a = NashNumPy.ndarray()
            a.iarray( res )
            return a
        # Заменяем оператор умножения
        def __mul__(self,new):
            if len(new.array)!=len(self.array[0]):
                return("Матрицы не могут быть перемножены")
            r1 = len(self.array)    # количество строк в первой матрице
            c1 = len(self.array[0]) # количество столбцов в 1
            r2=c1
            c2=len(new.array[0]) # количество столбцов во 2ой матрице
            res = []
            for z in range(r1):
                t=[]
                for j in range(c2):
                    s = 0
                    for i in range(c1):
                        s = s + self.array[z][i] * new.array[i][j]
                    t.append(s)
                res.append(t)
            a = NashNumPy.ndarray()
            a.iarray(res)
            return a            
        # Произведение Адамара ("/")
        def __truediv__(self,new):
            if self.shape != new.shape:
                return("Матрицы не могут быть перемножены")
            if self.ndim == 2:
                res = [[self.array[i][j] * new.array[i][j] for j in range (len(self.array[0]))] for i in range(len(self.array))] 
            else:
                res = list(map(mul,self.array,new.array))
            a = NashNumPy.ndarray()
            a.iarray(res)
            return a
        # Вертикальное присоединение
        def vstack(self,new):
            r1 = 1 if self.ndim == 1 else self.shape[0]
            c1 = self.shape[0] if self.ndim == 1 else self.shape[1]
            r2 = 1 if new.ndim == 1 else new.shape[0]
            c2 = new.shape[0] if new.ndim == 1 else new.shape[1]
            if c1 != c2:
                return("Несовместимые массивы: не совпадает число столбцов %d и %d") % (c1,c2)
            res = []
            if r1 == 1:
                res.append(self.array)
            else:
                for row in self.array:
                    res.append(row)
            if r2 == 1:
                res.append(new.array)
            else:
                for row in new.array:
                    res.append(row)
            a = NashNumPy.ndarray()
            a.iarray(res)
            return a
        # Горизонтальное присоединение
        def hstack(self,new):
            r1 = 1 if self.ndim == 1 else self.shape[0]
            c1 = self.shape[0] if self.ndim == 1 else self.shape[1]
            r2 = 1 if new.ndim == 1 else new.shape[0]
            c2 = new.shape[0] if new.ndim == 1 else new.shape[1]
            if r1 != r2:
                return("Несовместимые массивы: не совпадает число строк %d и %d") % (r1,r2)
            if r1 == 1:
                res = []
                for i in range(c1):
                    res.append(self.array[i])
                for i in range(c2):
                    res.append(new.array[i])
            else:
                res = list(range(r1))
                for i in range(r1):
                    res[i] = list(range(c1+c2))
                for i in range(r1):
                    for j in range(c1):
                        res[i][j] = self.array[i][j]
                    for j in range(c2):
                        res[i][c1+j] = new.array[i][j]
            a = NashNumPy.ndarray()
            a.iarray(res)
            return a
                
    def array(data):
        a = NashNumPy.ndarray()
        a.iarray(data)
        return a
    
    def zeros(size):
        a = NashNumPy.ndarray()
        a.izeros(size)
        return a
    
    def ones(size):
        a = NashNumPy.ndarray()
        a.iones(size)
        return a
    
def inc(a):
    return a+1
def dec(a):
    return a-1
 

In [11]:
a = NashNumPy.ones(10)
print("a:"),print(a)

b = NashNumPy.zeros([3,4])
print("\nb:"),print(b)

b2 = NashNumPy.ones(4)
c = NashNumPy.array([[1,2,3],[4,5,6],[7,8,0]])
d = NashNumPy.array([1,2,3,4,5,6,7,8,9,10])
a.array[0] = 30
b.array[0][0] = 100
a.vectorize(inc)
b.vectorize(dec)

print("\na.vectorize(inc):")
print(a)

print("\nb.vectorize(dec):")
print(b)

print("\nc:")
print(c)

print("\nd:")
print(d)

print("\nshapes a b c",a.shape,b.shape,c.shape)
print("\na+a")
print(a + a)

print("\nb+b")
print(b + b)

print("\na-a")
print(a - a)

print("\nb-b")
print(b - b)

print("\nc*c")
print(c * c)

print("\na умн.Адамара a")
print( a / a)

print("\nc умн.Адамара c")
print(c / c)

print("\na.hstack(a)")
print(a.hstack(a))

print("\nb.hstack(c)")
print(b.hstack(c))

print("\na.vstack(a)")
print(a.vstack(a))

print("\nb.vstack(b)")
print(b.vstack(b))

a:
[ 1 1 1 1 1 1 1 1 1 1 ]

b:
[ 0 0 0 0 ]
[ 0 0 0 0 ]
[ 0 0 0 0 ]

a.vectorize(inc):
[ 31  2  2  2  2  2  2  2  2  2 ]

b.vectorize(dec):
[ 99 -1 -1 -1 ]
[ -1 -1 -1 -1 ]
[ -1 -1 -1 -1 ]

c:
[ 1 2 3 ]
[ 4 5 6 ]
[ 7 8 0 ]

d:
[  1  2  3  4  5  6  7  8  9 10 ]

shapes a b c (10,) (3, 4) (3, 3)

a+a
[ 62  4  4  4  4  4  4  4  4  4 ]

b+b
[ 198  -2  -2  -2 ]
[  -2  -2  -2  -2 ]
[  -2  -2  -2  -2 ]

a-a
[ 0 0 0 0 0 0 0 0 0 0 ]

b-b
[ 0 0 0 0 ]
[ 0 0 0 0 ]
[ 0 0 0 0 ]

c*c
[ 30 36 15 ]
[ 66 81 42 ]
[ 39 54 69 ]

a умн.Адамара a
[ 961   4   4   4   4   4   4   4   4   4 ]

c умн.Адамара c
[  1  4  9 ]
[ 16 25 36 ]
[ 49 64  0 ]

a.hstack(a)
[ 31  2  2  2  2  2  2  2  2  2 31  2  2  2  2  2  2  2  2  2 ]

b.hstack(c)
[ 99 -1 -1 -1  1  2  3 ]
[ -1 -1 -1 -1  4  5  6 ]
[ -1 -1 -1 -1  7  8  0 ]

a.vstack(a)
[ 31  2  2  2  2  2  2  2  2  2 ]
[ 31  2  2  2  2  2  2  2  2  2 ]

b.vstack(b)
[ 99 -1 -1 -1 ]
[ -1 -1 -1 -1 ]
[ -1 -1 -1 -1 ]
[ 99 -1 -1 -1 ]
[ -1 -1 -1 -1 ]
[ -1 -1 -1 -1 ]
